env: prod
namespace: smb-workload
imagePullSecrets: registry-github
frontend:
  name: frontend
  image: ghcr.io/3rdyearproj-mark-ohm-banjo/int366-client:prod
  port: 80
backend:
  name: backend
  image: ghcr.io/3rdyearproj-mark-ohm-banjo/int366-backend:prod
  port: 3000
ingress:
  name: ingressctl
  host: sharemybook.ddns.net
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "5m"
    nginx.org/client-max-body-size: "5m"
  frontend:
    path: /?(.*)
  backend:
    path: /backend/?(.*)
    
extraEnv:
  COMMIT_ID: CHANGME

