version: "3"
services:
  backend:
    image: ghcr.io/3rdyearproj-mark-ohm-banjo/int365-backend:dev
    container_name: backend
    expose:
      - "3000"
    networks:
      my_network:
        ipv4_address: 172.22.0.4
networks:
  default:
    external:
      name: my_network
  my_network:
    external: true
