import {
  faCheck,
  faDownload,
  faXmark,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faDragon,
  faBook,
  faGhost,
  faHandHoldingHand,
  faPenNib,
  faFilter,
  faBars,
  faHome,
  faUser,
  faBell,
  faFire,
  faCalendarDays,
  faSearch,
  faSquareRootVariable,
  faGraduationCap,
  faBuildingColumns,
  faFlask,
  faHeart,
  faHatWizard,
  faFaceLaugh,
  faPuzzlePiece,
  faGem,
  faBrain,
  faDog,
  faLanguage,
  faBookBookmark,
  faLock,
  faEnvelope,
  faPhone,
  faLocationDot,
  faSignOut,
  faSignIn,
  faSort,
  faQuestion,
  faTrash,
  faFaceSadTear,
  faPenToSquare,
  faUserShield,
  faPaperPlane,
  faEye,
  faEyeSlash,
  faFlag,
  faClock,
  faCircleCheck,
  faCircleXmark,
  faExclamationCircle,
} from '@fortawesome/free-solid-svg-icons'

import {faFacebook, faGoogle} from '@fortawesome/free-brands-svg-icons'

export const ICONS = {
  faCheck,
  faDownload,
  faXmark,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faDragon,
  faGhost,
  faBook,
  faHandHoldingHand,
  faPenNib,
  faFilter,
  faBars,
  faHome,
  faUser,
  faBell,
  faFire,
  faCalendarDays,
  faSearch,
  faSquareRootVariable,
  faGraduationCap,
  faBuildingColumns,
  faFlask,
  faHeart,
  faHatWizard,
  faFaceLaugh,
  faPuzzlePiece,
  faGem,
  faBrain,
  faDog,
  faLanguage,
  faBookBookmark,
  faLock,
  faFacebook,
  faGoogle,
  faEnvelope,
  faPhone,
  faLocationDot,
  faSignOut,
  faSignIn,
  faSort,
  faQuestion,
  faTrash,
  faFaceSadTear,
  faPenToSquare,
  faUserShield,
  faPaperPlane,
  faEye,
  faEyeSlash,
  faFlag,
  faClock,
  faCircleCheck,
  faCircleXmark,
  faExclamationCircle,
}
export const ICON_SIZE = {
  xs: 'xs',
  sm: 'sm',
  md: 'md',
  lg: 'lg',
  xl: 'xl',
  '2x': '2x',
  '3x': '3x',
  '4x': '4x',
  '5x': '5x',
  '6x': '6x',
  '7x': '7x',
  '8x': '8x',
  '9x': '9x',
  '10x': '10x',
}
