name: backend
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/3rdyearproj-mark-ohm-banjo/int366-backend:prod

  deploy:
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy
        uses: glopezep/helm@v1.7.1
        with:
          helm: helm3
          release: sharemybook
          namespace: smb-workload
          chart: k8s-helm-ssl/helm
          value-files: k8s-helm-ssl/helm-values/values-smb-prod.yaml
          values: |
            {
              "extraEnv": {
                "COMMIT_ID": "${{ github.sha }}"
              }
            }
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"


